# Form implementation generated from reading ui file 'mainui.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title_frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.title_frame.setGeometry(QtCore.QRect(0, 0, 801, 24))
        self.title_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.title_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.title_frame.setObjectName("title_frame")
        self.Icon = QtWidgets.QLabel(parent=self.title_frame)
        self.Icon.setGeometry(QtCore.QRect(0, 0, 24, 24))
        self.Icon.setText("")
        self.Icon.setPixmap(QtGui.QPixmap("Resources/icons/icon.png"))
        self.Icon.setScaledContents(False)
        self.Icon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Icon.setObjectName("Icon")
        self.label_2 = QtWidgets.QLabel(parent=self.title_frame)
        self.label_2.setGeometry(QtCore.QRect(24, 0, 101, 24))
        self.label_2.setObjectName("label_2")
        self.exit_button = QtWidgets.QPushButton(parent=self.title_frame)
        self.exit_button.setGeometry(QtCore.QRect(770, 0, 24, 24))
        self.exit_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Resources/icons/exit.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.exit_button.setIcon(icon)
        self.exit_button.setObjectName("exit_button")
        self.fullscreen_button = QtWidgets.QPushButton(parent=self.title_frame)
        self.fullscreen_button.setGeometry(QtCore.QRect(746, 0, 24, 24))
        self.fullscreen_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Resources/icons/maximise.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.fullscreen_button.setIcon(icon1)
        self.fullscreen_button.setObjectName("fullscreen_button")
        self.minimise_button = QtWidgets.QPushButton(parent=self.title_frame)
        self.minimise_button.setGeometry(QtCore.QRect(722, 0, 24, 24))
        self.minimise_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Resources/icons/minimise.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.minimise_button.setIcon(icon2)
        self.minimise_button.setObjectName("minimise_button")
        self.main_frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.main_frame.setGeometry(QtCore.QRect(0, 30, 801, 551))
        self.main_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.main_frame.setObjectName("main_frame")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Draw App"))
